//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb_1._6.FamousPeopleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FamousPeopleService.FamousPeopleDiedInPlanecrashSoap")]
    public interface FamousPeopleDiedInPlanecrashSoap {
        
        // CODEGEN: Generating message contract since element name year from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonFromList", ReplyAction="*")]
        Labb_1._6.FamousPeopleService.GetPersonFromListResponse GetPersonFromList(Labb_1._6.FamousPeopleService.GetPersonFromListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonFromList", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb_1._6.FamousPeopleService.GetPersonFromListResponse> GetPersonFromListAsync(Labb_1._6.FamousPeopleService.GetPersonFromListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonFromListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonFromList", Namespace="http://tempuri.org/", Order=0)]
        public Labb_1._6.FamousPeopleService.GetPersonFromListRequestBody Body;
        
        public GetPersonFromListRequest() {
        }
        
        public GetPersonFromListRequest(Labb_1._6.FamousPeopleService.GetPersonFromListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonFromListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        public GetPersonFromListRequestBody() {
        }
        
        public GetPersonFromListRequestBody(string year) {
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonFromListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonFromListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb_1._6.FamousPeopleService.GetPersonFromListResponseBody Body;
        
        public GetPersonFromListResponse() {
        }
        
        public GetPersonFromListResponse(Labb_1._6.FamousPeopleService.GetPersonFromListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonFromListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPersonFromListResult;
        
        public GetPersonFromListResponseBody() {
        }
        
        public GetPersonFromListResponseBody(string GetPersonFromListResult) {
            this.GetPersonFromListResult = GetPersonFromListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FamousPeopleDiedInPlanecrashSoapChannel : Labb_1._6.FamousPeopleService.FamousPeopleDiedInPlanecrashSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FamousPeopleDiedInPlanecrashSoapClient : System.ServiceModel.ClientBase<Labb_1._6.FamousPeopleService.FamousPeopleDiedInPlanecrashSoap>, Labb_1._6.FamousPeopleService.FamousPeopleDiedInPlanecrashSoap {
        
        public FamousPeopleDiedInPlanecrashSoapClient() {
        }
        
        public FamousPeopleDiedInPlanecrashSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FamousPeopleDiedInPlanecrashSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FamousPeopleDiedInPlanecrashSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FamousPeopleDiedInPlanecrashSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb_1._6.FamousPeopleService.GetPersonFromListResponse Labb_1._6.FamousPeopleService.FamousPeopleDiedInPlanecrashSoap.GetPersonFromList(Labb_1._6.FamousPeopleService.GetPersonFromListRequest request) {
            return base.Channel.GetPersonFromList(request);
        }
        
        public string GetPersonFromList(string year) {
            Labb_1._6.FamousPeopleService.GetPersonFromListRequest inValue = new Labb_1._6.FamousPeopleService.GetPersonFromListRequest();
            inValue.Body = new Labb_1._6.FamousPeopleService.GetPersonFromListRequestBody();
            inValue.Body.year = year;
            Labb_1._6.FamousPeopleService.GetPersonFromListResponse retVal = ((Labb_1._6.FamousPeopleService.FamousPeopleDiedInPlanecrashSoap)(this)).GetPersonFromList(inValue);
            return retVal.Body.GetPersonFromListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb_1._6.FamousPeopleService.GetPersonFromListResponse> Labb_1._6.FamousPeopleService.FamousPeopleDiedInPlanecrashSoap.GetPersonFromListAsync(Labb_1._6.FamousPeopleService.GetPersonFromListRequest request) {
            return base.Channel.GetPersonFromListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb_1._6.FamousPeopleService.GetPersonFromListResponse> GetPersonFromListAsync(string year) {
            Labb_1._6.FamousPeopleService.GetPersonFromListRequest inValue = new Labb_1._6.FamousPeopleService.GetPersonFromListRequest();
            inValue.Body = new Labb_1._6.FamousPeopleService.GetPersonFromListRequestBody();
            inValue.Body.year = year;
            return ((Labb_1._6.FamousPeopleService.FamousPeopleDiedInPlanecrashSoap)(this)).GetPersonFromListAsync(inValue);
        }
    }
}
