//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb_1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WCF_Labbar_Labb1Soap")]
    public interface WCF_Labbar_Labb1Soap {
        
        // CODEGEN: Generating message contract since element name WeatherResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Weather", ReplyAction="*")]
        Labb_1.ServiceReference1.WeatherResponse Weather(Labb_1.ServiceReference1.WeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Weather", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb_1.ServiceReference1.WeatherResponse> WeatherAsync(Labb_1.ServiceReference1.WeatherRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Weather", Namespace="http://tempuri.org/", Order=0)]
        public Labb_1.ServiceReference1.WeatherRequestBody Body;
        
        public WeatherRequest() {
        }
        
        public WeatherRequest(Labb_1.ServiceReference1.WeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WeatherRequestBody {
        
        public WeatherRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb_1.ServiceReference1.WeatherResponseBody Body;
        
        public WeatherResponse() {
        }
        
        public WeatherResponse(Labb_1.ServiceReference1.WeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WeatherResult;
        
        public WeatherResponseBody() {
        }
        
        public WeatherResponseBody(string WeatherResult) {
            this.WeatherResult = WeatherResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCF_Labbar_Labb1SoapChannel : Labb_1.ServiceReference1.WCF_Labbar_Labb1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCF_Labbar_Labb1SoapClient : System.ServiceModel.ClientBase<Labb_1.ServiceReference1.WCF_Labbar_Labb1Soap>, Labb_1.ServiceReference1.WCF_Labbar_Labb1Soap {
        
        public WCF_Labbar_Labb1SoapClient() {
        }
        
        public WCF_Labbar_Labb1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCF_Labbar_Labb1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCF_Labbar_Labb1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCF_Labbar_Labb1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb_1.ServiceReference1.WeatherResponse Labb_1.ServiceReference1.WCF_Labbar_Labb1Soap.Weather(Labb_1.ServiceReference1.WeatherRequest request) {
            return base.Channel.Weather(request);
        }
        
        public string Weather() {
            Labb_1.ServiceReference1.WeatherRequest inValue = new Labb_1.ServiceReference1.WeatherRequest();
            inValue.Body = new Labb_1.ServiceReference1.WeatherRequestBody();
            Labb_1.ServiceReference1.WeatherResponse retVal = ((Labb_1.ServiceReference1.WCF_Labbar_Labb1Soap)(this)).Weather(inValue);
            return retVal.Body.WeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb_1.ServiceReference1.WeatherResponse> Labb_1.ServiceReference1.WCF_Labbar_Labb1Soap.WeatherAsync(Labb_1.ServiceReference1.WeatherRequest request) {
            return base.Channel.WeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb_1.ServiceReference1.WeatherResponse> WeatherAsync() {
            Labb_1.ServiceReference1.WeatherRequest inValue = new Labb_1.ServiceReference1.WeatherRequest();
            inValue.Body = new Labb_1.ServiceReference1.WeatherRequestBody();
            return ((Labb_1.ServiceReference1.WCF_Labbar_Labb1Soap)(this)).WeatherAsync(inValue);
        }
    }
}
