//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb_1._6.PeoplePassedAway2010Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeoplePassedAway2010Service.PeopleWhoPassedAway2010Soap")]
    public interface PeopleWhoPassedAway2010Soap {
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersonWhoPassedAway", ReplyAction="*")]
        Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayResponse PersonWhoPassedAway(Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersonWhoPassedAway", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayResponse> PersonWhoPassedAwayAsync(Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersonWhoPassedAwayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersonWhoPassedAway", Namespace="http://tempuri.org/", Order=0)]
        public Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequestBody Body;
        
        public PersonWhoPassedAwayRequest() {
        }
        
        public PersonWhoPassedAwayRequest(Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonWhoPassedAwayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        public PersonWhoPassedAwayRequestBody() {
        }
        
        public PersonWhoPassedAwayRequestBody(string date) {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersonWhoPassedAwayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersonWhoPassedAwayResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayResponseBody Body;
        
        public PersonWhoPassedAwayResponse() {
        }
        
        public PersonWhoPassedAwayResponse(Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonWhoPassedAwayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PersonWhoPassedAwayResult;
        
        public PersonWhoPassedAwayResponseBody() {
        }
        
        public PersonWhoPassedAwayResponseBody(string PersonWhoPassedAwayResult) {
            this.PersonWhoPassedAwayResult = PersonWhoPassedAwayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PeopleWhoPassedAway2010SoapChannel : Labb_1._6.PeoplePassedAway2010Service.PeopleWhoPassedAway2010Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeopleWhoPassedAway2010SoapClient : System.ServiceModel.ClientBase<Labb_1._6.PeoplePassedAway2010Service.PeopleWhoPassedAway2010Soap>, Labb_1._6.PeoplePassedAway2010Service.PeopleWhoPassedAway2010Soap {
        
        public PeopleWhoPassedAway2010SoapClient() {
        }
        
        public PeopleWhoPassedAway2010SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeopleWhoPassedAway2010SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleWhoPassedAway2010SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleWhoPassedAway2010SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayResponse Labb_1._6.PeoplePassedAway2010Service.PeopleWhoPassedAway2010Soap.PersonWhoPassedAway(Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequest request) {
            return base.Channel.PersonWhoPassedAway(request);
        }
        
        public string PersonWhoPassedAway(string date) {
            Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequest inValue = new Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequest();
            inValue.Body = new Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequestBody();
            inValue.Body.date = date;
            Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayResponse retVal = ((Labb_1._6.PeoplePassedAway2010Service.PeopleWhoPassedAway2010Soap)(this)).PersonWhoPassedAway(inValue);
            return retVal.Body.PersonWhoPassedAwayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayResponse> Labb_1._6.PeoplePassedAway2010Service.PeopleWhoPassedAway2010Soap.PersonWhoPassedAwayAsync(Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequest request) {
            return base.Channel.PersonWhoPassedAwayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayResponse> PersonWhoPassedAwayAsync(string date) {
            Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequest inValue = new Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequest();
            inValue.Body = new Labb_1._6.PeoplePassedAway2010Service.PersonWhoPassedAwayRequestBody();
            inValue.Body.date = date;
            return ((Labb_1._6.PeoplePassedAway2010Service.PeopleWhoPassedAway2010Soap)(this)).PersonWhoPassedAwayAsync(inValue);
        }
    }
}
