//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1.ServiceReferenceWeather {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWeather.WeatherServiceSoap")]
    public interface WeatherServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetWeatherResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeather", ReplyAction="*")]
        Labb1.ServiceReferenceWeather.GetWeatherResponse GetWeather(Labb1.ServiceReferenceWeather.GetWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb1.ServiceReferenceWeather.GetWeatherResponse> GetWeatherAsync(Labb1.ServiceReferenceWeather.GetWeatherRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeather", Namespace="http://tempuri.org/", Order=0)]
        public Labb1.ServiceReferenceWeather.GetWeatherRequestBody Body;
        
        public GetWeatherRequest() {
        }
        
        public GetWeatherRequest(Labb1.ServiceReferenceWeather.GetWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWeatherRequestBody {
        
        public GetWeatherRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb1.ServiceReferenceWeather.GetWeatherResponseBody Body;
        
        public GetWeatherResponse() {
        }
        
        public GetWeatherResponse(Labb1.ServiceReferenceWeather.GetWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWeatherResult;
        
        public GetWeatherResponseBody() {
        }
        
        public GetWeatherResponseBody(string GetWeatherResult) {
            this.GetWeatherResult = GetWeatherResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherServiceSoapChannel : Labb1.ServiceReferenceWeather.WeatherServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServiceSoapClient : System.ServiceModel.ClientBase<Labb1.ServiceReferenceWeather.WeatherServiceSoap>, Labb1.ServiceReferenceWeather.WeatherServiceSoap {
        
        public WeatherServiceSoapClient() {
        }
        
        public WeatherServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb1.ServiceReferenceWeather.GetWeatherResponse Labb1.ServiceReferenceWeather.WeatherServiceSoap.GetWeather(Labb1.ServiceReferenceWeather.GetWeatherRequest request) {
            return base.Channel.GetWeather(request);
        }
        
        public string GetWeather() {
            Labb1.ServiceReferenceWeather.GetWeatherRequest inValue = new Labb1.ServiceReferenceWeather.GetWeatherRequest();
            inValue.Body = new Labb1.ServiceReferenceWeather.GetWeatherRequestBody();
            Labb1.ServiceReferenceWeather.GetWeatherResponse retVal = ((Labb1.ServiceReferenceWeather.WeatherServiceSoap)(this)).GetWeather(inValue);
            return retVal.Body.GetWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb1.ServiceReferenceWeather.GetWeatherResponse> Labb1.ServiceReferenceWeather.WeatherServiceSoap.GetWeatherAsync(Labb1.ServiceReferenceWeather.GetWeatherRequest request) {
            return base.Channel.GetWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb1.ServiceReferenceWeather.GetWeatherResponse> GetWeatherAsync() {
            Labb1.ServiceReferenceWeather.GetWeatherRequest inValue = new Labb1.ServiceReferenceWeather.GetWeatherRequest();
            inValue.Body = new Labb1.ServiceReferenceWeather.GetWeatherRequestBody();
            return ((Labb1.ServiceReferenceWeather.WeatherServiceSoap)(this)).GetWeatherAsync(inValue);
        }
    }
}
