//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb_1._5.NameDayServise {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NameDayServise.NamnsdagarServiceSoap")]
    public interface NamnsdagarServiceSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNameForDate", ReplyAction="*")]
        Labb_1._5.NameDayServise.GetNameForDateResponse GetNameForDate(Labb_1._5.NameDayServise.GetNameForDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNameForDate", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb_1._5.NameDayServise.GetNameForDateResponse> GetNameForDateAsync(Labb_1._5.NameDayServise.GetNameForDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameForDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNameForDate", Namespace="http://tempuri.org/", Order=0)]
        public Labb_1._5.NameDayServise.GetNameForDateRequestBody Body;
        
        public GetNameForDateRequest() {
        }
        
        public GetNameForDateRequest(Labb_1._5.NameDayServise.GetNameForDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNameForDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public GetNameForDateRequestBody() {
        }
        
        public GetNameForDateRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameForDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNameForDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb_1._5.NameDayServise.GetNameForDateResponseBody Body;
        
        public GetNameForDateResponse() {
        }
        
        public GetNameForDateResponse(Labb_1._5.NameDayServise.GetNameForDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNameForDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNameForDateResult;
        
        public GetNameForDateResponseBody() {
        }
        
        public GetNameForDateResponseBody(string GetNameForDateResult) {
            this.GetNameForDateResult = GetNameForDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NamnsdagarServiceSoapChannel : Labb_1._5.NameDayServise.NamnsdagarServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NamnsdagarServiceSoapClient : System.ServiceModel.ClientBase<Labb_1._5.NameDayServise.NamnsdagarServiceSoap>, Labb_1._5.NameDayServise.NamnsdagarServiceSoap {
        
        public NamnsdagarServiceSoapClient() {
        }
        
        public NamnsdagarServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NamnsdagarServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NamnsdagarServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NamnsdagarServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb_1._5.NameDayServise.GetNameForDateResponse Labb_1._5.NameDayServise.NamnsdagarServiceSoap.GetNameForDate(Labb_1._5.NameDayServise.GetNameForDateRequest request) {
            return base.Channel.GetNameForDate(request);
        }
        
        public string GetNameForDate(string input) {
            Labb_1._5.NameDayServise.GetNameForDateRequest inValue = new Labb_1._5.NameDayServise.GetNameForDateRequest();
            inValue.Body = new Labb_1._5.NameDayServise.GetNameForDateRequestBody();
            inValue.Body.input = input;
            Labb_1._5.NameDayServise.GetNameForDateResponse retVal = ((Labb_1._5.NameDayServise.NamnsdagarServiceSoap)(this)).GetNameForDate(inValue);
            return retVal.Body.GetNameForDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb_1._5.NameDayServise.GetNameForDateResponse> Labb_1._5.NameDayServise.NamnsdagarServiceSoap.GetNameForDateAsync(Labb_1._5.NameDayServise.GetNameForDateRequest request) {
            return base.Channel.GetNameForDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb_1._5.NameDayServise.GetNameForDateResponse> GetNameForDateAsync(string input) {
            Labb_1._5.NameDayServise.GetNameForDateRequest inValue = new Labb_1._5.NameDayServise.GetNameForDateRequest();
            inValue.Body = new Labb_1._5.NameDayServise.GetNameForDateRequestBody();
            inValue.Body.input = input;
            return ((Labb_1._5.NameDayServise.NamnsdagarServiceSoap)(this)).GetNameForDateAsync(inValue);
        }
    }
}
