//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb_1._2.AdditionServiceTwoNumbers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdditionServiceTwoNumbers.AdditionServiceSoap")]
    public interface AdditionServiceSoap {
        
        // CODEGEN: Generating message contract since element name AddTwoNumbersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersResponse AddTwoNumbers(Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersResponse> AddTwoNumbersAsync(Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoNumbers", Namespace="http://tempuri.org/", Order=0)]
        public Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequestBody Body;
        
        public AddTwoNumbersRequest() {
        }
        
        public AddTwoNumbersRequest(Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int x;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int y;
        
        public AddTwoNumbersRequestBody() {
        }
        
        public AddTwoNumbersRequestBody(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersResponseBody Body;
        
        public AddTwoNumbersResponse() {
        }
        
        public AddTwoNumbersResponse(Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddTwoNumbersResult;
        
        public AddTwoNumbersResponseBody() {
        }
        
        public AddTwoNumbersResponseBody(string AddTwoNumbersResult) {
            this.AddTwoNumbersResult = AddTwoNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdditionServiceSoapChannel : Labb_1._2.AdditionServiceTwoNumbers.AdditionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdditionServiceSoapClient : System.ServiceModel.ClientBase<Labb_1._2.AdditionServiceTwoNumbers.AdditionServiceSoap>, Labb_1._2.AdditionServiceTwoNumbers.AdditionServiceSoap {
        
        public AdditionServiceSoapClient() {
        }
        
        public AdditionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdditionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersResponse Labb_1._2.AdditionServiceTwoNumbers.AdditionServiceSoap.AddTwoNumbers(Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequest request) {
            return base.Channel.AddTwoNumbers(request);
        }
        
        public string AddTwoNumbers(int x, int y) {
            Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequest inValue = new Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequest();
            inValue.Body = new Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersResponse retVal = ((Labb_1._2.AdditionServiceTwoNumbers.AdditionServiceSoap)(this)).AddTwoNumbers(inValue);
            return retVal.Body.AddTwoNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersResponse> Labb_1._2.AdditionServiceTwoNumbers.AdditionServiceSoap.AddTwoNumbersAsync(Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequest request) {
            return base.Channel.AddTwoNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersResponse> AddTwoNumbersAsync(int x, int y) {
            Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequest inValue = new Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequest();
            inValue.Body = new Labb_1._2.AdditionServiceTwoNumbers.AddTwoNumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((Labb_1._2.AdditionServiceTwoNumbers.AdditionServiceSoap)(this)).AddTwoNumbersAsync(inValue);
        }
    }
}
